---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-webserver
  namespace: gitops
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/webserver: glob:master-*
spec:
  selector:
    matchLabels:
      app: gitops-webserver
  replicas: 3
  template:
    metadata:
      labels:
        app: gitops-webserver
    spec:
      containers:
      - name: webserver
        image: luanngominh/gitops:flux-a7af1e3
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: regcred
