---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: gitops
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/webserver: regexp:^1.1*
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: webserver
        image: nginx:1.16-perl
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: gitops
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30880
