apiVersion: v1
kind: Service
metadata:
  name: gitops-webserver
  namespace: gitops
spec:
  type: NodePort
  selector:
    app: gitops-webserver
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30800
