os: linux
language: go

go:
  - 1.x

jobs:
  include:
    - stage: "build"
      name: "Delivery to docker hub"
      services:
        - docker
      script:
        - dockerpass=`echo $DOCKER_PASSWORD | base64 -d`
        - dockeruser=`echo $DOCKER_USER | base64 -d`
        - echo "$dockerpass" | docker login --username "$dockeruser" --password-stdin
        - /bin/bash build.sh


notifications:
   email:
      recipients:
      - ngominhluanbox@gmail.com
      on_success: always
      on_failure: always


