os: linux
language: go

go:
  - 1.x

jobs:
  include:
    - stage: "build"
      name: "Delivery to docker hub"
      services:
        - docker
      script:
        - dockerpass=`echo $DOCKER_PASSWORD | base64 -d`
        - dockeruser=`echo $DOCKER_USERNAME | base64 -d`
        - echo "$dockerpass" | docker login --username "$dockeruser" --password-stdin
        - /bin/bash build.sh
      

