apiVersion: v1
kind: Secret
metadata:
  name: regcred
  namespace: gitops
data:
  .dockerconfigjson: "ewoJImF1dGhzIjogewoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CgkJCSJhdXRoIjogImJIVmhibTVuYjIxcGJtZzZObVF4TmpkbVpUa3ROVGswWXkwME4yUmxMV0V3WXpBdFpUbGhOVGt5T1RWaVptTmsiCgkJfQoJfSwKCSJIdHRwSGVhZGVycyI6IHsKCQkiVXNlci1BZ2VudCI6ICJEb2NrZXItQ2xpZW50LzE5LjAzLjUtY2UgKGxpbnV4KSIKCX0KfQ=="
type: kubernetes.io/dockerconfigjson
